#!/usr/bin/env python3
"""
Citizen Ledger — the findings manifest, globbed from docs/ on disk.

WHY THIS EXISTS. findings.html carried a hand-written list of investigation
documents, and on 2026-07-29 there were 34 finding documents on disk and 33
listed: the A-2 entity-page finding was published in the repository and
invisible on the page that exists to index findings. Nothing failed. The
page looked complete because a complete-looking page is what an enumerated
list produces right up to the moment it is wrong.

That is the FIFTH instance of one defect in this project — the enumerated
page list, the enumerated digest list, the enumerated GATED list, the
enumerated conditional branch (OPEN.md 2s), and now the enumerated document
index. See OPEN.md 2y.

WHAT IT DOES NOT DO. It does not generate the editorial entries. Those
carry verified figures and a stated decision, and a machine cannot write
them from the prose — the findings index was built by checking 34 documents'
numbers by hand, and that work is not reproducible by parsing. So the page
keeps its written entries and gets its COMPLETENESS from here: this manifest
names every document, the page compares it against what it has already
linked, and anything unwritten is listed rather than omitted.

A finding is therefore visible on the index the moment its document lands,
with a link and its own first sentence, whether or not anyone has written
the editorial entry yet.
"""
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

# These are the project's standing records, not investigations. findings.html
# links them in its own header, so they are not part of the finding count.
# Declared here rather than pattern-matched: a new standing record should
# have to be added deliberately, and a new FINDING should need no edit at all.
NOT_FINDINGS = {"OPEN.md", "SCOPE.md", "SECURITY.md", "GUARDRAILS.md"}


def title_of(text, fallback):
    """The document's own H1, minus any trailing em-dash subtitle."""
    m = re.search(r"^#\s+(.+)$", text, re.M)
    return m.group(1).strip() if m else fallback


def first_sentence(text):
    """The first real sentence of prose, for a reader deciding whether to open
    it. Skips the H1, any italic dateline, and any table or list."""
    body = re.sub(r"^#.*$", "", text, count=1, flags=re.M)
    for para in re.split(r"\n\s*\n", body):
        p = para.strip()
        if not p or p.startswith(("*", "|", "-", ">", "#", "```")):
            continue
        p = re.sub(r"\s+", " ", re.sub(r"[*_`\[\]]|\(docs/[^)]*\)", "", p))
        m = re.match(r"(.{40,400}?[.!?])(\s|$)", p)
        return (m.group(1) if m else p[:300]).strip()
    return ""


def main():
    write = "--write" in sys.argv
    docs = sorted(p for p in DOCS.glob("*.md") if p.name not in NOT_FINDINGS)
    if not docs:
        raise SystemExit("no finding documents under docs/ — refusing to write "
                         "an empty manifest, which would silently empty the "
                         "findings index")
    out = []
    for p in docs:
        t = p.read_text(encoding="utf-8")
        out.append({
            "doc": f"docs/{p.name}",
            "title": title_of(t, p.stem.replace("_", " ").title()),
            "lede": first_sentence(t),
            "bytes": len(t.encode("utf-8")),
        })
    payload = {
        "meta": {
            "generated": date.today().isoformat(),
            "count": len(out),
            "note": "Globbed from docs/ on disk by "
                    "pipeline/build_findings_manifest.py. findings.html keeps "
                    "its hand-written entries — those carry verified figures — "
                    "and uses this only for COMPLETENESS: any document here "
                    "that the page has not written up is listed rather than "
                    "omitted. A finding cannot be published and invisible.",
            "excluded": sorted(NOT_FINDINGS),
        },
        "findings": out,
    }
    js = ("/* GENERATED by pipeline/build_findings_manifest.py — do not edit. "
          "Globbed from docs/*.md; see that file for why the list is derived "
          "rather than written. */\nwindow.CA_FINDINGS_MANIFEST = "
          + json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
          + ";\n")
    for f in out:
        print(f"  {f['doc']:44} {f['bytes']/1024:>6,.1f} KB  {f['title'][:44]}")
    print(f"\n{len(out)} finding documents ({len(js)/1024:,.1f} KB manifest)")
    if not write:
        print("Dry run — nothing written. Use --write.")
        return
    (ROOT / "findings-manifest.js").write_text(js, encoding="utf-8")
    print(f"Wrote {ROOT / 'findings-manifest.js'}")


if __name__ == "__main__":
    main()
