#!/usr/bin/env python3
"""
Generate county-geo.js — boundaries for California's counties, as
GeoJSON for the MapLibre map's county layer.

    python3 pipeline/make_county_boundaries.py [--tolerance 0.2]

Source: U.S. Census Bureau cartographic boundary file
cb_2023_us_county_500k (public domain), filtered to STATEFP 06.
Reuses the stdlib shp/dbf reader and Douglas-Peucker from the city
generator, with the same tolerance semantics.

All 57 filing counties must match county-data.js by name or the write
fails with a named report. San Francisco's polygon IS included — it
would otherwise be a hole in the map — but carries
`"pointer": "city"` instead of a county record: the UI must route it
to the Cities layer (it files as a consolidated city-county) and must
never select it as a county. Properties are ONLY
{slug, name, clng, clat[, pointer]} — no financial fields.
"""

import argparse
import io
import json
import sys
import urllib.request
import zipfile
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from integrity import stamp                                      # noqa: E402
from make_ca_outline import read_dbf_records, read_shp_polygons   # noqa: E402
from make_city_boundaries import simplify_city                    # noqa: E402
from fetch_city_data import _norm_place                           # noqa: E402

URL = "https://www2.census.gov/geo/tiger/GENZ2023/shp/cb_2023_us_county_500k.zip"
ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "county-geo.js"


def main():
    ap = argparse.ArgumentParser(description="Rebuild county-geo.js (GeoJSON)")
    ap.add_argument("--tolerance", type=float, default=0.2)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    text = (ROOT / "county-data.js").read_text(encoding="utf-8")
    county_data = json.loads(text[text.index("=") + 1: text.rindex(";")])
    name_to_slug = {c["name"]: slug for slug, c in county_data["counties"].items()}

    print("Downloading " + URL, file=sys.stderr)
    req = urllib.request.Request(URL, headers={"User-Agent": "ca-ledger-pipeline/1.0"})
    data = urllib.request.urlopen(req, timeout=180).read()
    z = zipfile.ZipFile(io.BytesIO(data))
    shp = z.read([n for n in z.namelist() if n.endswith(".shp")][0])
    dbf = z.read([n for n in z.namelist() if n.endswith(".dbf")][0])
    rows = read_dbf_records(dbf)
    shapes = read_shp_polygons(shp)

    lookup = {}
    for r, s in zip(rows, shapes):
        if r.get("STATEFP") != "06":
            continue
        lookup[_norm_place(r["NAME"].strip())] = s

    features, unmatched, total_pts = [], [], 0

    def add(name, slug, extra=None):
        nonlocal total_pts
        s = lookup.get(_norm_place(name))
        if s is None:
            unmatched.append(name)
            return
        polys, clng, clat = simplify_city(s, args.tolerance)
        total_pts += sum(len(ring) - 1 for poly in polys for ring in poly)
        props = {"slug": slug, "name": name, "clng": clng, "clat": clat}
        if extra:
            props.update(extra)
        features.append({"type": "Feature", "properties": props,
                         "geometry": {"type": "Polygon", "coordinates": polys[0]}
                         if len(polys) == 1 else
                         {"type": "MultiPolygon", "coordinates": polys}})

    for name, slug in sorted(name_to_slug.items()):
        add(name, slug)
    # San Francisco: on the map, but routed to the Cities layer — the
    # consolidated city-county is never a selectable county record.
    add("San Francisco", "san-francisco", {"pointer": "city"})

    if unmatched:
        sys.exit("COUNTY BOUNDARY MATCH FAILED — nothing written:\n  "
                 + "\n  ".join(unmatched))

    payload = {
        "meta": {
            "source": "U.S. Census Bureau cartographic boundary file "
                      "cb_2023_us_county_500k (public domain), California "
                      "counties, GeoJSON (lon/lat, 5 decimals)",
            "generated": date.today().isoformat(),
            "toleranceViewboxUnits": args.tolerance,
        },
        "type": "FeatureCollection",
        "features": features,
    }
    stamp(payload)
    body = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    print(f"{len(features)} county boundaries · {total_pts:,} points · "
          f"payload ≈ {(len(body) + 60) / 1024:.0f} KB", file=sys.stderr)
    if args.dry_run:
        return
    header = ("/* GENERATED by pipeline/make_county_boundaries.py on "
              f"{date.today().isoformat()} — do not edit by hand. */\n")
    OUT_PATH.write_text(header + "window.CA_COUNTY_GEO = " + body + ";\n",
                        encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({OUT_PATH.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
